name: build

on: 
  workflow_dispatch:
    inputs:      
      GPIO_KEY :
        description: 'reset putton'
        required: true
        type: string
        default: '3'
      breed-name:
        description: 'Breed bootloader name'
        required: true
        type: string
        default: 'breed-mt7621-xiaomi-r3g.bin'


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin ccache curl binwalk  
          
           wget https://breed.hackpascal.net/'${{ inputs.breed-name }}'
           ./breed_magic --src '${{ inputs.breed-name }}' --dst breed_mod.bin -r '${{ inputs.GPIO_KEY }}'

      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: ./*.bin
