name: build

on: 
  workflow_dispatch:
    inputs:      
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'
      GPIO_KEY :
        description: 'reset putton'
        required: true
        type: string
        default: '3'
      breed-name:
        description: 'Breed bootloader name'
        required: true
        type: string
        default: 'breed-mt7621-hiwifi-hc5962.bin'


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin ccache curl binwalk  
          
           wget https://breed.hackpascal.net/'${{ inputs.breed-name }}'
           ./breed_magic --src '${{ inputs.breed-name }}' --dst breed_mod.bin -r '${{ inputs.GPIO_KEY }}'

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}


      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: ./*.bin
